version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/authPollApp
    networks:
      - webnet

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - webnet

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait \$${!}; done"
    networks:
      - webnet

networks:
  webnet:

volumes:
  mongodb_data:
