version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: pollapp_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - webnet

  app:
    build: .
    container_name: pollapp_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: pollapp_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - webnet

  certbot:
    image: certbot/certbot:latest
    container_name: pollapp_certbot
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --no-self-upgrade; sleep 12h & wait \$${!}; done;"
    networks:
      - webnet

volumes:
  mongodb_data:

networks:
  webnet:
